version: '3.7'
x-extra_hosts:
  &default-extra_hosts
  - "krb5.lc.cluster:172.10.0.2"
  - "hdfs-nn.lc.cluster:172.10.0.3"
  - "hdfs-dn.lc.cluster:172.10.0.4"
  - "hive-server.lc.cluster:172.10.0.5"
  - "hive-metastore.lc.cluster:172.10.0.6"
  - "hive-metastore-db.lc.cluster:172.10.0.7"
  - "nodemanager.lc.cluster:172.10.0.8"
  - "resourcemanager.lc.cluster:172.10.0.9"
  - "historyserver.lc.cluster:172.10.0.10"
services:
  krb5:
    image: krb5:0.1
    container_name: krb5
    hostname: krb5.lc.cluster
    extra_hosts: *default-extra_hosts
    privileged: true
    tty: true
    stdin_open: true
    networks:
      cl-net:
        ipv4_address: 172.10.0.2
  hdfs-nn:
    image: hadoop-namenode:2.6
    container_name: hdfs-nn
    hostname: hdfs-nn.lc.cluster
    extra_hosts: *default-extra_hosts
    privileged: true
    ports:
      - "5045:5005"
    tty: true
    stdin_open: true
    depends_on:
      - krb5
    environment:
      - HDFS_CONF_dfs_webhdfs_enabled=false
    networks:
      cl-net:
        ipv4_address: 172.10.0.3
    command: sh -c "wait-for-it.sh krb5.lc.cluster:22 -- run.sh && tail -f /opt/hadoop-2.6.5/logs/hadoop.log"
  hdfs-dn:
    image: hadoop-datanode:2.6
    container_name: hdfs-dn
    hostname: hdfs-dn.lc.cluster
    extra_hosts: *default-extra_hosts
    privileged: true
    ports:
      - "5055:5005"
    tty: true
    stdin_open: true
    depends_on:
      - hdfs-nn
    networks:
      cl-net:
        ipv4_address: 172.10.0.4
    command: sh -c "wait-for-it.sh krb5.lc.cluster:22 -- run.sh && tail -f /opt/hadoop-2.6.5/logs/hadoop.log"
  hive-server:
    image: hadoop-hive:2.3.2
    hostname: hive-server.lc.cluster
    container_name: hive-server
    extra_hosts: *default-extra_hosts
    depends_on:
      - krb5
      - hive-metastore
    privileged: true
    tty: true
    stdin_open: true
    command: "wait-for-it.sh hdfs-nn.lc.cluster:8020 -- /usr/local/bin/run.sh hiveserver2"
    ports:
      - "5155:5005"
    env_file:
      - ./hadoop/hive/hive.env
    environment:
      SERVICE_PRECONDITION: "hive-metastore.lc.cluster:9083"
    networks:
      cl-net:
        ipv4_address: 172.10.0.5
  hive-metastore:
    image: hadoop-hive:2.3.2
    hostname: hive-metastore.lc.cluster
    container_name: hive-metastore
    extra_hosts: *default-extra_hosts
    depends_on:
      - krb5
    privileged: true
    tty: true
    stdin_open: true
    command: "wait-for-it.sh hdfs-nn.lc.cluster:8020 -- /usr/local/bin/run.sh hivemetastore"
    ports:
      - "5105:5005"
    env_file:
      - ./hadoop/hive/hive.env
    environment:
      SERVICE_PRECONDITION: "hive-metastore-db.lc.cluster:5432"
    networks:
      cl-net:
        ipv4_address: 172.10.0.6
  hive-metastore-db:
    image: bde2020/hive-metastore-postgresql:2.3.0
    hostname: hive-metastore-db.lc.cluster
    container_name: hive-metastore-db
    ports:
      - "5433:5432"
    extra_hosts: *default-extra_hosts
    privileged: true
    tty: true
    stdin_open: true
    networks:
      cl-net:
        ipv4_address: 172.10.0.7
  nodemanager:
    image: hadoop-nodemanager:2.0.0
    hostname: nodemanager.lc.cluster
    container_name: nodemanager
    extra_hosts: *default-extra_hosts
    depends_on:
      - krb5
    privileged: true
    tty: true
    stdin_open: true
    command: "wait-for-it.sh krb5.lc.cluster:22 -- /usr/local/bin/run.sh"
    env_file:
      - ./hadoop/hive/hive.env
    networks:
      cl-net:
        ipv4_address: 172.10.0.20
    ports:
      - "8042:8042"
  resourcemanager:
    image: hadoop-resourcemanager:2.0.0
    hostname: resourcemanager.lc.cluster
    container_name: resourcemanager
    extra_hosts: *default-extra_hosts
    restart: always
    depends_on:
      - krb5
    privileged: true
    tty: true
    stdin_open: true
    command: "wait-for-it.sh hdfs-dn.lc.cluster:50475 --  -- /usr/local/bin/run.sh"
    env_file:
      - ./hadoop/hive/hive.env
    ports:
      - "8088:8088"
    networks:
      cl-net:
        ipv4_address: 172.10.0.21
  historyserver:
    image: hadoop-historyserver:2.0.0
    hostname: historyserver.lc.cluster
    container_name: historyserver
    extra_hosts: *default-extra_hosts
    depends_on:
      - krb5
    privileged: true
    tty: true
    stdin_open: true
    env_file:
      - ./hadoop/hive/hive.env
    ports:
      - "8188:8188"
    command: sh -c "wait-for-it.sh krb5.lc.cluster:22 -- /usr/local/bin/run.sh"
    networks:
      cl-net:
        ipv4_address: 172.10.0.22
networks:
  cl-net:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16