version: '3.7'
services:
  krb5:
    image: krb5:0.1
    build:
      context: krb5
  core:
    image: core:0.1
    build:
      context: core
  hadoop-base:
    image: hadoop-base:2.6
    build:
      context: hadoop/base
  hadoop-namenode:
    image: hadoop-namenode:2.6
    build:
      context: hadoop/namenode
    depends_on:
      - hadoop-base
  hadoop-datanode:
    image: hadoop-datanode:2.6
    build:
      context: hadoop/datanode
    depends_on:
      - hadoop-base
  hadoop-hive:
    image: hadoop-hive:2.3.2
    build:
      context: hadoop/hive
  hadoop-nodemanager:
    image: hadoop-nodemanager:2.0.0
    build:
      context: hadoop/hive
      dockerfile: nodemanager/Dockerfile
  hadoop-resourcemanager:
    image: hadoop-resourcemanager:2.0.0
    build:
      context: hadoop/hive
      dockerfile: resourcemanager/Dockerfile
  hadoop-historyserver:
    image: hadoop-historyserver:2.0.0
    build:
      context: hadoop/hive
      dockerfile: historyserver/Dockerfile